create database csw default character set utf8 collate utf8_general_ci;
USE csw;

CREATE TABLE TB_HYDRONODE_B (
    NDCD VARCHAR(20) NOT NULL,
    NDNM VARCHAR(20) NOT NULL,
    NDTP INTEGER NOT NULL,
    RVCD VARCHAR(8),
    RMCHA DOUBLE(7,2),
    LGTD DOUBLE(10,6),
    LTTD DOUBLE(10,6),
    DWNDCD VARCHAR(20),
    SYMLEV DOUBLE(1,0),
    PRIMARY KEY(NDCD)
)DEFAULT CHARSET=utf8;

CREATE TABLE TB_MODEL_B (
    MODELCD VARCHAR(10) NOT NULL,
    MODELNM VARCHAR(50),
    MODELINF VARCHAR(100),
    MODELTP INTEGER,
    PRIMARY KEY(MODELCD)
)DEFAULT CHARSET=utf8;

